config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :projects do
  resources :file_test do
    collection do
      get 'create_or_update'
      post 'update_active_columns'
    end
  end
end

app/models/active_file_plan_column.rb
class ActiveFilePlanColumn < ActiveRecord::Base
  unloadable
  DEFAULT_ACTIVE_COLUMNS = %w(url
      functional_test
      test_in_ff
      test_in_ie
      test_in_ch
      test_in_sf
      test_in_mobile
      test_in_real_device
      internal_control
      client_note)

  ALL_COLUMNS = ['url',
                 'functional_test',
                 'test_in_ff',
                 'test_in_ch',
                 'test_in_ie',
                 'test_in_sf',
                 'test_in_mobile',
                 'test_in_real_device',
                 'raspberry',
                 'vega',
                 'thomson',
                 'android',
                 'ready_for_demo',
                 'internal_control',
                 'client_note']

  def self.active_columns(project)
    active_columns = where(project_id: project.id).active.pluck(:column_name)
    if active_columns.blank?
      active_columns = DEFAULT_ACTIVE_COLUMNS
    end
    active_columns
  end

  def self.active
    where(is_active: true)
  end
end

app/models/test_plan.rb
class TestPlan < ActiveRecord::Base
  unloadable
  belongs_to :issue
  include Redmine::SafeAttributes
  safe_attributes 'issue_id',
                  'functional_test',
                  'test_in_ff',
                  'test_in_ch',
                  'test_in_ie',
                  'test_in_sf',
                  'test_in_mobile',
                  'test_in_real_device',
                  'raspberry',
                  'vega',
                  'thomson',
                  'android',
                  'ready_for_demo',
                  'url',
                  'internal_control',
                  'client_note'

  RAS     = ['RAS',     0]
  PASS    = ['PASS',    1]
  PLANNED = ['PLANNED', 2]
  FAILED  = ['FAILED',  3]

  STATUS = [RAS, PASS, PLANNED, FAILED]

  validates_presence_of :issue_id



end

app/controllers/file_test_controller.rb
class FileTestController < ApplicationController
  unloadable

  before_filter :find_project
  before_filter :find_issue, only: [:create_or_update]
  before_filter :authorize, except: [:update_active_columns]
  before_filter :require_admin, only: [:update_active_columns]


  def update_active_columns
    columns = ActiveFilePlanColumn::ALL_COLUMNS
    columns.each do |c|
      a = ActiveFilePlanColumn.where(project_id: @project.id, column_name: c).first_or_initialize
      a.is_active = params[c] ?  true : false
      a.save
    end
    redirect_to back_url
  end


  def index
    @issues = @project.issues.order('issues.id DESC').
        where(status_id: IssueStatus.where.not(is_closed: true).pluck(:id) ).
        includes(:test_plan).references(:test_plan)

    @active_columns = ActiveFilePlanColumn.active_columns(@project)
    @last_update = TestPlan.where(project_id: @project.id).order('updated_on DESC').first.try(:updated_on).to_s
  end

  def create_or_update
    @test_plan = @issue.test_plan || TestPlan.new(issue_id: @issue.id)
    @test_plan.project_id = @project.id

    @type = params[:type]
    @value = params[:value]
    #check type if is safe
    if @test_plan.safe_attribute?(@type)
      if @type.in?(['url', 'client_note'])
        @test_plan.send("#{@type}=", @value)
      else
        @test_plan.send("#{@type}=", @value) if TestPlan::STATUS.map{|v| v.last }.include?(@value.to_i)
      end
    end
    @test_plan.save

    @last_update = TestPlan.where(project_id: @project.id).order('updated_on DESC').first.try(:updated_on).to_s
    respond_to do |format|
      format.js {}
    end
  end

  def destroy

  end

  private

  def find_project
    @project = Project.find(params[:project_id])
  rescue
    render_404
  end

  def find_issue
    @issue = @project.issues.find(params[:issue_id])
  rescue
    render_404
  end


end

app/helpers/file_test_helper.rb
module FileTestHelper
end

app/views/file_test/create_or_update.js.erb
<% unless @type.in?(['url', 'client_note']) %>
a = $(".issue_test_plan[data-issueid='" + <%= @issue.id %> + "']").find('.<%= @type %>')
a.removeClass("test_result_0");
a.removeClass("test_result_1");
a.removeClass("test_result_2");
a.removeClass("test_result_3");
a.addClass("test_result_<%= @value %>");
<% end  %>

$('#last_update').html("Last update:  <%= @last_update %>")

app/views/file_test/index.html.erb
<style>
  select {
    border: 1px solid #fff;
    background-color: rgba(255,255,255,.5);
    padding: 0px;
    margin-left: 5px;
    margin-top: 5px;
  }

  select option{
    background-color: transparent !important;
    border: 1px solid #e4e4e4;
    color: #000;
    -webkit-appearance: none;
    -moz-appearance: none;
  }
  .test_result_0{
    background-color: grey;
  }
  .test_result_1{
    background-color: #00aa55;
  }
  .test_result_2{
    background-color: #f59e00 ;
  }
  .test_result_3{
    background-color: #8b0000;
  }
</style>
<div id="last_update" >
  Last update: <%= @last_update %>
</div>
<div id="filter" >
 <%= select_tag(:status, options_for_select(IssueStatus.pluck(:name, :id)), include_blank: true) %>
</div>
<div class="autoscroll">
  <table class="list issues odd-even" >
    <thead>
    <tr>
      <th style="min-width: 125px;">Issue</th>
      <th style="min-width: 125px;">Assigné</th>
      <% columns = ActiveFilePlanColumn::ALL_COLUMNS %>
      <% columns.each do |column| %>
          <% if @active_columns.include?(column) %>
              <th><%= l(column) %></th>
          <% end %>
      <% end %>
    </tr>
    </thead>
    <tbody>
    <% @issues.each do |issue| %>
        <% plan = issue.test_plan || TestPlan.new(issue_id: issue.id) %>
        <tr class="issue_test_plan <%= cycle('odd', 'even') %> issue_status_<%= issue.status_id %>"   data-issueid="<%= issue.id %>">
          <td><%= "[#{issue.status}]" %> <%=link_to_issue issue %></td>
          <td><%= link_to_user issue.assigned_to %></td>
          <% columns.each do |column| %>
              <% if @active_columns.include?(column) %>
                  <% if column.in?(['url', 'client_note']) %>
                      <td>
                        <%= text_field_tag column, plan.send(column) %>
                      </td>
                  <% else %>
                      <td class="test_result_<%= plan.send(column) %> <%= column %>">
                        <%= select_tag(column, options_for_select(TestPlan::STATUS, selected: plan.send(column)), {include_blank: true}) %>
                      </td>
                  <% end %>
              <% end %>
          <% end %>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

<script>
  $(document).ready(function(){
      $('#status').on('change', function(){
          val = $(this).val();
          $('.issue_test_plan').hide()
          $('.issue_status_'+ val).show()
      })
    $('.issue_test_plan').find('select').on('change', function(e){
      issue = $(this).parents('.issue_test_plan').data('issueid');
      type = $(this).attr('id');
      value = $(this).val();
      $.getScript('<%= create_or_update_project_file_test_index_path(@project, format: :js) %>'+ '?issue_id='+issue+ "&type=" +type+ "&value="+ value);
    })
    $('.issue_test_plan').find('input').on('change', function(e){
      issue = $(this).parents('.issue_test_plan').data('issueid');
      type = $(this).attr('id');
      value = $(this).val();
      $.getScript('<%= create_or_update_project_file_test_index_path(@project, format: :js) %>'+ '?issue_id='+issue+ "&type=" +type+ "&value="+ value);
    })
  })
</script>

app/views/projects/settings/_test_file.html.erb
<% columns = ActiveFilePlanColumn::ALL_COLUMNS %>
<% @active_columns = ActiveFilePlanColumn.active_columns(@project) %>
<%= form_tag update_active_columns_project_file_test_index_path(@project) do %>
  <% columns.each do |column| %>
    <%= check_box_tag(column, column, @active_columns.include?(column)  ) %> <%= l(column) %> <br/>
  <% end %>
    <%= submit_tag :save %>
<% end %>